### ISSUE TITLE
Can I make the transferred buffer writable / readable again?

### ISSUE THREAD

**Issue by baptistemanson** [domenic/proposal-arraybuffer-transfer#2]
```js
let buffer = new ArrayBuffer();

function validateAndWrite(arrayBuffer, filename) {
  const transferred = arrayBuffer.transfer();
  await isEverythingOk(transferred, filename);
  await writeFileInBuffer(transferred, filename);
  return transferred;
}
/** other stuff **/
// get back the transferred
buffer = await validateAndWrite(buffer, filename)
```
Would that be the correct approach?

**Comment by domenic** [comment]
Yep, that'd work.

To clarify, you can never make the exact same `ArrayBuffer` object readable/writable again. That would be a much bigger change to how ArrayBuffers work. But you can reassign a variable (`buffer` in your example) to the newly-created `ArrayBuffer` object, that points to the same memory.
