### ISSUE TITLE
Add example of how this is handled today with things like postMessage

### ISSUE THREAD

**Issue by jdalton** [domenic/proposal-arraybuffer-transfer#4]
The current proposal hints at this but since I can see some folks having q's around expected behavior, could this proposal stress prior art in the web space _(maybe with an example)_ and draw a connection to the expected behaviors here.

**Comment by domenic** [comment]
Withdrawing the proposal. To do this on the web or Node or Deno, use `const transferred = structuredClone(arrayBuffer, { transfer: arrayBuffer })`.
