### ISSUE TITLE
Transfer repo ownership

### ISSUE THREAD

**Issue by gesa** [domenic/proposal-arraybuffer-transfer#8]
Cleaning up our [active proposals document](/tc39/proposals) and noticed this was stage 2 and not yet in the TC39 org. Could you update the README to reflect this and transfer ownership to tc39-transfer?

tyvm!

**Comment by UInt2048** [comment]
@domenic, you have been contributing even today. Do you plan to transfer this proposal to TC39?

**Comment by domenic** [comment]
Withdrawing the proposal, so no longer relevant.
